/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a imapproveradaptor_p.h:imapproveradaptor.cpp -c IMApproverAdaptor imapprover.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "imapproveradaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IMApproverAdaptor
 */

IMApproverAdaptor::IMApproverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IMApproverAdaptor::~IMApproverAdaptor()
{
    // destructor
}

void IMApproverAdaptor::acceptCall(const QString &accountId, const QString &contactId)
{
    // handle method call com.meego.app.imapprover.acceptCall
    QMetaObject::invokeMethod(parent(), "acceptCall", Q_ARG(QString, accountId), Q_ARG(QString, contactId));
}

