/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a imapproveradaptor_p.h:imapproveradaptor.cpp -c IMApproverAdaptor imapprover.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef IMAPPROVERADAPTOR_P_H_1307061345
#define IMAPPROVERADAPTOR_P_H_1307061345

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meego.app.imapprover
 */
class IMApproverAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meego.app.imapprover")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meego.app.imapprover\">\n"
"    <method name=\"acceptCall\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"accountId\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"contactId\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    IMApproverAdaptor(QObject *parent);
    virtual ~IMApproverAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void acceptCall(const QString &accountId, const QString &contactId);
Q_SIGNALS: // SIGNALS
};

#endif
