/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a imdbusadaptor_p.h:imdbusadaptor.cpp -c IMDBusAdaptor im.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "imdbusadaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IMDBusAdaptor
 */

IMDBusAdaptor::IMDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IMDBusAdaptor::~IMDBusAdaptor()
{
    // destructor
}

void IMDBusAdaptor::dumpLogs()
{
    // handle method call com.meego.app.im.dumpLogs
    QMetaObject::invokeMethod(parent(), "dumpLogs");
}

void IMDBusAdaptor::reportMissedCalls(const QString &accountId, const QStringList &contacts, const QStringList &times)
{
    // handle method call com.meego.app.im.reportMissedCalls
    QMetaObject::invokeMethod(parent(), "reportMissedCalls", Q_ARG(QString, accountId), Q_ARG(QStringList, contacts), Q_ARG(QStringList, times));
}

void IMDBusAdaptor::showChat(const QString &accountId, const QString &contactId)
{
    // handle method call com.meego.app.im.showChat
    QMetaObject::invokeMethod(parent(), "showChat", Q_ARG(QString, accountId), Q_ARG(QString, contactId));
}

bool IMDBusAdaptor::userBusyCalling()
{
    // handle method call com.meego.app.im.userBusyCalling
    bool busy;
    QMetaObject::invokeMethod(parent(), "userBusyCalling", Q_RETURN_ARG(bool, busy));
    return busy;
}

