#!/bin/sh

THEPID=`pidof meego-ux-daemon meego-qml-launcher | cut -d " " -f 1`
export `xargs --null --max-args=1 echo < /proc/$THEPID/environ | grep DBUS_SESSION`

qdbus | grep com.meego.app.im > /dev/null
if [ $? -eq 0 ]; then
    qdbus com.meego.app.im /com/meego/app/im com.meego.app.im.dumpLogs
    mv /tmp/log-im.* .
    ls -l log-im.*
else
    echo ""
    echo "ERROR: MeeGo App IM is not running."
    echo "   Please make sure you start the application before running this script."
    echo ""
fi
